# Generated by Django 6.1.1 on 2026-10-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='material',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='quantity',
        ),
        migrations.CreateModel(
            name='InquiryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('deadline', models.DateField(null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='inquiries.inquiry')),
            ],
        ),
    ]
